### ISSUE TITLE
获取运行状态图失败

### ISSUE THREAD

**Issue by Kiana1314** [lgc2333/nonebot-plugin-picstatus#15]
```py
11-20 19:23:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot-plugin-picstatus.nonebot_plugin_picstatus.__main__)
11-20 19:23:37 [ERROR] nonebot_plugin_picstatus | 获取运行状态图失败
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\bot\NB2\venv\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\bot\NB2\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\bot\NB2\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\bot\NB2\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\bot\NB2\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\bot\NB2\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\bot\NB2\venv\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\bot\NB2\venv\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\bot\NB2\venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\bot\NB2\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\bot\NB2\venv\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\bot\NB2\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\bot\NB2\venv\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\bot\NB2\venv\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\bot\NB2\venv\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\bot\NB2\venv\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\bot\NB2\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\bot\NB2\nb\.\nonebot-plugin-picstatus\nonebot_plugin_picstatus\__main__.py", line 47, in _
    ret = await get_stat_pic(bot, pic)
  File "C:\bot\NB2\nb\.\nonebot-plugin-picstatus\nonebot_plugin_picstatus\draw.py", line 559, in get_stat_pic
    ret: List[Optional[Image.Image]] = await asyncio.gather(  # noqa
  File "C:\bot\NB2\nb\.\nonebot-plugin-picstatus\nonebot_plugin_picstatus\draw.py", line 315, in draw_disk_usage
    await asyncio.gather(get_disk_usage(), get_disk_io())
  File "C:\bot\NB2\nb\.\nonebot-plugin-picstatus\nonebot_plugin_picstatus\draw.py", line 278, in get_disk_usage
    if _r := match_list_regexp(config.ps_ignore_parts, _d.mountpoint):
  File "C:\bot\NB2\nb\.\nonebot-plugin-picstatus\nonebot_plugin_picstatus\util.py", line 84, in match_list_regexp
    if m := re.search(r, txt):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\re.py", line 200, in search
    return _compile(pattern, flags).search(string)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 512, in _parse
    sourceget()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 257, in get
    self.__next()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 246, in __next
    raise error("bad escape (end of pattern)",
re.error: bad escape (end of pattern) at position 2
11-20 19:23:37 [ERROR] nonebot_plugin_picstatus | 网页 Google(https://google.com) 访问失败
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 485, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bot\NB2\venv\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 282, in _loop_reading
    length = fut.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 489, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\bot\NB2\venv\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\bot\NB2\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\bot\NB2\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\bot\NB2\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\bot\NB2\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\bot\NB2\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\bot\NB2\venv\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\bot\NB2\venv\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\bot\NB2\venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\bot\NB2\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\bot\NB2\venv\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\bot\NB2\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\bot\NB2\nb\.\nonebot-plugin-picstatus\nonebot_plugin_picstatus\draw.py", line 438, in get_result
    async with c.get(
  File "C:\bot\NB2\venv\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\bot\NB2\venv\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\bot\NB2\venv\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\bot\NB2\venv\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\bot\NB2\venv\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\bot\NB2\venv\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\bot\NB2\venv\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host google.com:443 ssl:default [指定的网络名不再可用。]
11-20 19:23:37 [INFO] nonebot | Matcher(type='message', module=nonebot-plugin-picstatus.nonebot_plugin_picstatus.__main__) running complete
11-20 19:23:38 [INFO] nonebot_plugin_picstatus | 网卡 Loopback Pseudo-Interface 1 匹配 ^Loopback，忽略
11-20 19:23:38 [INFO] nonebot_plugin_picstatus | 网卡 isatap.{7F4F0912-3910-4F2F-89EA-DF38E0C7DF2D} 匹配 isatap....，忽略
```

**Comment by lgc2333** [comment]
你写的正则表达式出问题了

**Comment by Kiana1314** [comment]
是网络名还是盘符？

**Comment by Kiana1314** [comment]
![%HQ(K1H56A(DPK5}4V2SO`Q](https://user-images.githubusercontent.com/107671434/202904685-709c8694-0fca-4156-91af-f08bfb72c73b.png)

**Comment by lgc2333** [comment]
请把`D:\\`改成`D:\\\\`或者直接改成`^D:`
由于在新版本里我用了正则表达式匹配，而\正好是正则表达式和json字符串的转义字符，所以需要在json字符串里转义两次

**Comment by Kiana1314** [comment]
好了好了  除了谷歌的地址不能访问报错外  可以出图了  谢谢大佬

**Comment by lgc2333** [comment]
> 好了好了 除了谷歌的地址不能访问报错外 可以出图了 谢谢大佬

可以设置`PROXY`
