### ISSUE TITLE
获取运行状态图片失败

### ISSUE THREAD

**Issue by 502milk** [lgc2333/nonebot-plugin-picstatus#20]
`01-19 21:41:45 [ERROR] nonebot_plugin_picstatus | 获取运行状态图失败
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\502\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\502\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\502\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\502\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\502\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\502\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1919, in _run_once
    handle._run()
  File "C:\Users\502\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\nonebot_plugin_picstatus\__main__.py", line 47, in _
    ret = await get_stat_pic(bot, pic)
  File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\nonebot_plugin_picstatus\draw.py", line 559, in get_stat_pic
    ret: List[Optional[Image.Image]] = await asyncio.gather(  # noqa
  File "C:\Users\502\Desktop\nonebot\testbot\.venv\Lib\site-packages\nonebot_plugin_picstatus\draw.py", line 81, in draw_header
    list(config.nickname)[0]
IndexError: list index out of range
01-19 21:41:46 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_picstatus.__main__) running complete
01-19 21:41:46 [INFO] nonebot_plugin_picstatus | 网卡 Loopback Pseudo-Interface 1 匹配 ^Loopback，忽略`

**Comment by lgc2333** [comment]
你.env是不是没有`nickname`配置项……
行，我修

**Comment by 502milk** [comment]
哦草·-·
我的锅
~~因为懒得写~~
